### ISSUE TITLE
False Positives: Many seeds in picture

### ISSUE THREAD

**Issue by RussellJimmies** [ai-cfia/nachet-model#12] opened 2023-11-22 22:47 UTC
**Description**
When there are a large number of seeds, the ability to select them all goes down, and the identifications become less reliable. This is 11 seeds, but only 10 identifications were given, and not all IDs are correct.

**Expected behavior**
All seeds correctly classified with high confidence score.

**Actual Behavior**
False positives.

**Supporting Images**
To better understand the issue, please add screenshots:
* **Results**:
![image](https://github.com/ai-cfia/nachet-model/assets/88112401/7ce18682-e2c3-4996-a914-00adad4fd6ed)

* **Source Image**: 
![0ebb8872b7ba8f8174f22a9b8aae41378b0de2700a41a078279bdcd58bebcce0](https://github.com/ai-cfia/nachet-model/assets/88112401/65358def-e6e9-4c2a-ac1d-8c1face441d9)

* **Microscope Settings**:  the microscope settings when the picture was taken.

**Comment by RussellJimmies** [comment] 2023-11-23 02:20
90% minimum confidence score:
![image](https://github.com/ai-cfia/nachet-model/assets/88112401/dba4525e-caf6-4ffa-ad2d-8ba32be1ec58)

**Comment by TaranMeyer** [comment] 2023-11-24 19:42
The elongate brownish seed labeled #3 in the first picture and #4 in the second picture, and identified as _Carduus nutans_ both times, is actually _Cirsium arvense_.

**Comment by MaxenceGui** [comment] 2024-04-08 20:16
Seems to be fixed by Swin Transformer Pipeline



![Image](https://github.com/ai-cfia/nachet-model/assets/96267006/59d6201c-79b7-49f3-aacc-ab666d241c1f)



![Image](https://github.com/ai-cfia/nachet-model/assets/96267006/bb9a3461-ab50-4f28-b771-5045c7d2b38a)

**Comment by MaxenceGui** [comment] 2024-04-09 20:53
@RussellJimmies can you test it again and validate that you have similar result so we can closing the issue?

**Comment by RussellJimmies** [comment] 2024-04-09 20:59
Just tested and got same results as you!

**Comment by MaxenceGui** [comment] 2024-04-10 11:47
Closing this issue as resolved since every bounding box is showing and @RussellJimmies confirms he can reproduce the result.

However, the models seems to have issues to identifies *Cirsium arvense*. For the first seeds, the species name is not in the top 5 result and for the second seeds, it's third on the list.

![Cirsium arvense](https://github.com/ai-cfia/nachet-model/assets/96267006/b9686f3d-674e-4d10-b347-6daa6c919bba)

Will wait on the user-acceptance test to open an issue on this specific seed as one false result is not representative of the hole performance of the model.

**Closed** 2024-04-10 11:47 UTC
Labels: bug, model

**Comment by TaranMeyer** [comment] 2024-04-10 15:11
FYI, the first seed, labeled #2, is _Carduus nutans_, not _Cirsium arvense_, so it has been identified correctly by the model.

**Comment by MaxenceGui** [comment] 2024-04-10 15:18
Oups, I read your last comment too fast.
